eureka:
  client:
    register-with-eureka: false
     
server:
  port: 8222
  
spring:
  application:
    name: gateway
    
  config:
    import: optional:configserver:http://localhost:8888
    
  cloud:
    gateway:
      routes:
        - id: reportes
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/reportes/**
            - Path=/api/v1/reportes
            
        - id: usuarios
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/usuarios/** 
            - Path=/api/v1/usuarios
            