eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
     
server:
  port: 8222
  
spring:
  application:
    name: gateway
    
  config:
    import: optional:configserver:http://localhost:8888
    
  cloud:
    gateway:
      mvc:
        routes:
          - id: usuarios
            uri: http://localhost:8090
            predicates:
              - Path=/api/v1/usuarios/**
              
          - id: reportes
            uri: http://localhost:8070
            predicates:
              - Path=/api/v1/reportes/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG