server:
  port: 8222

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuarios
          uri: lb://USUARIOS
          predicates:
            - Path=/api/v1/usuarios/**

        - id: reportes
          uri: lb://REPORTES
          predicates:
            - Path=/api/v1/reportes/**
          filters:
            - AuthFilter

        - id: defectos
          uri: lb://REPORTES
          predicates:
            - Path=/api/v1/defectos/**

        - id: servicio-conversion-moneda
          uri: lb://SERVICIO-CONVERSION-MONEDA
          predicates:
            - Path=/api/v1/conversion/**
            
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/auth/**    

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler: DEBUG
    org.springframework.web.reactive.DispatcherHandler: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    com.netflix.discovery: INFO