server:
  port: 8222

spring:
  application:
    name: gateway

  cloud:
    gateway:
      websocket:
        enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: frontend-public
          uri: lb://FRONTEND
          predicates:
            - Path=/login, /signup, /css/**, /js/**, /img/**

        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/auth/**

        - id: usuarios
          uri: lb://USUARIOS
          predicates:
            - Path=/api/v1/usuarios/**

        - id: reportes
          uri: lb://REPORTES
          predicates:
            - Path=/api/v1/reportes/**

        - id: defectos
          uri: lb://REPORTES
          predicates:
            - Path=/api/v1/defectos/**

        - id: piezas
          uri: lb://REPORTES
          predicates:
            - Path=/api/v1/piezas/**

        - id: tipo-defectos
          uri: lb://REPORTES
          predicates:
            - Path=/api/v1/tipo-defectos/**

        - id: servicio-conversion-moneda
          uri: lb://SERVICIO-CONVERSION-MONEDA
          predicates:
            - Path=/api/v1/conversion/**

        - id: frontend
          uri: lb://FRONTEND
          predicates:
            - Path=/**

        - id: notificaciones-ws
          uri: lb://NOTIFICACIONES-SERVICE
          predicates:
            - Path=/ws-notificaciones/**
          filters:
            - RewritePath=/ws-notificaciones(?<segment>/?.*), /ws-notificaciones${segment}

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler: DEBUG
    org.springframework.web.reactive.DispatcherHandler: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    com.netflix.discovery: INFO
