server:
  port: 8222

spring:
  application:
    name: gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: usuarios
            uri: lb://USUARIOS
            predicates:
              - Path=/api/v1/usuarios/**

          - id: reportes
            uri: lb://REPORTES
            predicates:
              - Path=/api/v1/reportes/**
              
          - id: defectos
            uri: lb://REPORTES
            predicates:
              - Path=/api/v1/defectos/**    

eureka:
  client:
    register-with-eureka: true  
    fetch-registry: true        
    service-url:
      defaultZone: http://localhost:8761/eureka/
