spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manufactura
    username: root
    password: messi
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  mvc:
    static-path-pattern: "/**"

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 8080
