eureka:
  instance:
    hostname: localhost
    
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8070
  
spring:
  application:
    name: reportes
    
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reportes
    username: root
    password: 1234
    
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect